danielbeardsley/cimpler

- bin/cimpler
- config.sample.js
- lib/http-trigger.js
- plugins/cli.js
The host was defaulting to `localhost`. This allows the host to be set
via the config file or a CLI param.
> Allow cimpler to connect to a remote cimpler server

- plugins/cli.js
Although IP whitelisting is a great feature, it's easier to implement at
the network level by opening and closing the entire port that cimpler is
listening on instead. Also, it was checking the current server's IP
address rather than the remote address so you'd have to add the current
server's IP to the list which allows access to from everywhere.
This just removes the whitelist entirely to simplify configuration.
> CLI: Remove IP whitelist

- plugins/git-build.js
- test/git-build.test.js
The `BUILD_COMMIT` environment variable wasn't set when manually
queueing a build via `cimpler build` so build scripts couldn't reliably
use it.
This updates the test so it was failing until I made the fix to set the
variable properly.
> Git build: Fix BUILD_COMMIT environment variable

- hooks/post-receive
- test/cli.test.js
- test/git-build.test.js
- test/post-recieve.test.js
Make the tests pass on Travis-CI in two ways:
* Ensure a local config.js is used during testing (causing failures)
* Disable one test cause the feature isn't available on Travis-CI
> Tests: Make them pass!

- plugins/git-build.js
- Allow the maxBuffer to be set through the user supplied config.
- Default the maxBuffer to 2MB (rather than the 200KB childProcess.exec default)
> git-build: Allow setting maxBuffer, Default to 2MB

- plugins/github-commit-status.js
The current repo regex won't handle a repo path that has a period before
the .git. For example if you have your repo as cimpler.js.git it would
not be parsed correctly until this change.
This regex was a bit funky since the browser, and node seem to disagree
on how to interpret this regex. This regex works as we intend it to on
node though.
> Modify repo regex to accept dots preceding .git

- lib/cimpler.js
- plugins/git-build.js
- test/cimpler.test.js
Previously `consumeBuild` only filtered based on a provided regular expression that would match against the repo name for individual builds. This pull adds the ability to define a function that is passed the build object and filter based on a returned boolean value.
> Cimpler: Allow filtering builds using a provided function

- lib/cimpler.js
- test/cimpler.test.js
The current behavior when determining if builds should be 'merged' is to compare the repo and branch of the two builds. If they're the same then we don't add the build to the queue but instead we replace the old build with the new one effectively 'merging' the two build requests. This works fine but there might be cases where we want to be able to build the same branch but at different points in the branch's commit history. 
This pull adds the ability to define a `shouldMergeBuilds` function in the config.js file that will be used to determine if two builds should be merged. Doing this allows users to more finely control when builds should be merged e.g. only 'merge' build requests when the _commits_ are the same in addition to the repo and branch.
CC @danielbeardsley
> Cimpler: Add ability to define shouldMergeBuilds function in config

- .travis.yml
- plugins/github.js
- test/github.test.js
The ref property contains a branch name and branch names can
contain forward slashes. Extract everything after the first two
slashes and use that as the prefix, while everything after is
treated as the branch name.
> Github plugin: support branches with forward slashes

- package.json
- plugins/git-build.js
Now we launch the processes in a new process group and kill
all the sub-procs in that group when we need to abort.
Previously we assumed bash and tried to use TRAP with `jobs -p`
which doesn't include any grandchildren procs.
> git-build: use process groups to manage subprocs

- plugins/github-commit-status.js
- test/github-commit-status.test.js
Now that github supports multiple statuses per commit,
let's let the user configure the 'context' name instead
of only reporting as 'default'.
Closes #69
> Github Commit Status: allow custom context

- bin/cimpler
- lib/git.js
- plugins/github-commit-status.js
- plugins/github.js
- test/github.test.js
Since we don't actually use the url for anything other than identifing
builds and parsing for user/repo to report commit status to github, we
might as well canonicalize them.
Previously several builds on the same branch could end up in the queue
because they were added under synonymous github remote urls (ssh vs
git vs https).
> Canonicalize github urls

- plugins/git-build.js
This ensures we clean files that are ignored in the branch we're coming from but aren't ignored in our new branch.
The old behavior caused problems when moving the location of a `node_modules` directory, which was ignored on each branch in the place that branch expects it. So we could have a situation where we have
```
master:.gitignore
/old/node_modules
branch:.gitignore
/node_modules
```
and when an `/old/node_modules` directory exists, it will not be deleted on checkout of `branch` (because it's ignored by `master`, which is still checked out at the point where we do the `git clean`). Worse still, when we go from `branch` back to another pull on `master` we leave the `/node_modules` directory behind. Potentially this breaks an unrelated branch, and there's not a good way to avoid it …
> Clean build directory after checkout and merge

- bin/cimpler
- lib/cimpler.js
- lib/config-provider.js
- lib/http-trigger.js
- server.js
- test/builds-status.test.js
- test/cimpler.test.js
- test/cli-plugin.test.js
- test/cli.test.js
- test/github.test.js
- test/post-recieve.test.js
- test/test-config.js
Instead of just assuming the config file will always be at
`./config.js`, take a CLI arg `--config=`... so we can talk to different
cimpler servers / launch multiple cimplers with one install.
Closes #89
> cli: take a --config=path option

- plugins/git-build.js
Previously, if a branch had a submodule but no entry in .gitmodules, it
would leave the CI directory in an unrecoverable state. The next branch
to come along would try `git submodule foreach` and git would complain
that there's no entry in .gitmodules.
This *clean before switching branches* thing was meant to help when
submodules had untracked files left behind, so I think it's worth
keeping.
> git-build: don't fail on cleaning failure

- config.sample.js
- plugins/git-build.js
So we can handle repos who's main branch is something other than master.
References: danielbeardsley/cimpler#78
> git-build: allow main branch to be configured

- lib/cimpler.js
- plugins/git-build.js
- plugins/shell.js
- test/cimpler.test.js
- test/cli-plugin.test.js
- test/cli.test.js
- test/git-build.test.js
Also, expose that in an ENV var in the git build plugin.
Some tests needed a bit of adjusting to deal with this.
It's useful to know how long a build has been queued.
> Cimpler: record build.queuedAt timestamp

- bin/cimpler
- plugins/git-build.js
- test/cli.test.js
- test/git-build.test.js
Coverage takes more than our default timeout of two hours which is set in 
the cimpler config. Add the ability to set the build timeout using a build
command argument.
Related: https://github.com/iFixit/ifixit/pull/35075
@danielbeardsley @BaseInfinity
> Add option to set build timeout with build argument

- config.sample.js
- plugins/git-build.js
If we pass in a `printHtml` config option, we surround the text
with `<pre>...</pre>` tags which signify preformatted text.
It's simple and should get the job done.
Also, updated the sample config.
Closes https://github.com/danielbeardsley/cimpler/issues/108
> git-build: Add html output support

- plugins/git-build.js
We want cimpler to be able to merge in master regardless of if
the repo's git hooks are set up correctly. Otherwise, if a built branch
sets up bad hooks, it can prevent further builds from even merging
in master.
> git-build: commit merge without running hooks

- config.sample.js
- plugins/git-build.js
Our coverage cimpler can't have master merged in because CodeCov
compares the coverage to the base commit of the branch. If we merged
in master, we could get many unrelated changes that would affect
our coverage numbers.
This allows us to configure cimpler to not merge in master.
> git-build: Add option to not merge in main branch/master

- plugins/git-build.js
- plugins/github.js
- plugins/shell.js
- test/git-build.test.js
- test/shell.test.js
We now send out an env var of the PR number. This is required for Coveralls because we
need to set the `CI_PULL_REQUEST` variable.
Also, added some tests. I thought this would have broke tests in a few other places but
that didn't seem to be the case.
CC @danielbeardsley @BaseInfinity
> Add PR number to build

- config.sample.js
- package.json
- plugins/github-commit-status.js
- test/github-commit-status.test.js
`github` has been deprecated in favor of `@octokit/rest`
> Replace github package with octokit

- plugins/git-build.js
Previously, we were only reading at the end, this would lock up the
process (preventing exit) if it produced more than {buffer size} of data.
Now we do the traditional data event listening and join them all at the
end. Note: we only do this when asked to, see individual commits for more info.
cr_req 1
Closes danielbeardsley/cimpler#121
> git-build: soak up data from child proc
